server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhshchMr/springcloudapplication.git
          search-paths: config
          username: 775383634@qq.com
          password: zhang80902417
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

